export const Users = [
    {
        id: 1,
        name: "Janet Stephen",
        username: "janet_22",
        email: "amber@logan.tv",
        profilePicture: "/assets/person/person1.jpg",
    },
    {
        id: 2,
        name: "Isabella Randy",
        username: "isabel_23",
        email: "isabella@randy.biz",
        profilePicture: "/assets/person/person2.jpg",
    },
    {
        id: 3,
        name: "Beverly Bruce",
        username: "beverly_24",
        email: "Sherwood@rosamond.me",
        profilePicture: "/assets/person/person3.jpg",
    },
    {
        id: 4,
        name: "Glenna Philip",
        username: "glenna_25",
        email: "Chaim_McDermott@dana.io",
        profilePicture: "/assets/person/person4.jpg",
    },
    // {
    //   id: 5,
    //   name: "Clementina Sean",
    //   username: "Alexis",
    //   email: "Rey.Padberg@karina.biz",
    //   profilePicture: "/assets/person/person5.jpg",
    // },
];
export const Usersonline = [
    {
        id: 1,
        name: "Leanne Graham",
        username: "Gloria",
        email: "Sincere@april.biz",
        profilePicture: "/assets/person/friend1.jpg",
    },
    {
        id: 2,
        name: "Ervin Howell",
        username: "Madison",
        email: "Shanna@melissa.tv",
        profilePicture: "/assets/person/friend2.jpg",
    },
    {
        id: 3,
        name: "Clementine Bauch",
        username: "Abigail",
        email: "Nathan@yesenia.net",
        profilePicture: "/assets/person/friend3.jpg",
    },
    {
        id: 4,
        name: "Patricia Lebsack",
        username: "Sophia",
        email: "Julianne.OConner@kory.org",
        profilePicture: "/assets/person/friend4.jpg",
    },
    {
        id: 5,
        name: "Chelsey Dietrich",
        username: "Marilyn",
        email: "Lucio_Hettinger@annie.ca",
        profilePicture: "/assets/person/friend5.jpg",
    },
    {
        id: 6,
        name: "Mrs. Dennis Schulist",
        username: "Doris",
        email: "Karley_Dach@jasper.info",
        profilePicture: "/assets/person/friend6.jpg",
    },
    {
        id: 7,
        name: "Kurtis Weissnat",
        username: "Rachel",
        email: "Telly.Hoeger@billy.biz",
        profilePicture: "/assets/person/friend7.jpg",
    },
    {
        id: 8,
        name: "Nicholas Runolfsdottir V",
        username: "Victoria",
        email: "Sherwood@rosamond.me",
        profilePicture: "/assets/person/friend8.jpg",
    },
    {
        id: 9,
        name: "Catherine",
        username: "Maria",
        email: "Chaim_McDermott@dana.io",
        profilePicture: "/assets/person/friend9.jpg",
    },
    {
        id: 10,
        name: "Clementina DuBuque",
        username: "Theresa",
        email: "Rey.Padberg@karina.biz",
        profilePicture: "/assets/person/friend10.jpg",
    },
    {
        id: 11,
        name: "Sharon Mattew",
        username: "Charlotte",
        email: "Rey.Padberg@karina.biz",
        profilePicture: "/assets/person/friend11.jpg",
    },
];

export const Posts = [
    {
        userId: 3,
        id: 1,
        title: "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
        body: "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
        photo: "/assets/posts/post1.jpg",
        date: "5 mins ago",
        like: "100",
        comment: "70",
    },
    {
        userId: 2,
        id: 2,
        title: "qui est esse",
        body:  "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla",
        photo: "/assets/posts/post2.jpg",
        date: "23 mins ago",
        like: "480",
        comment: "112",
    },
    {
        userId: 1,
        id: 3,
        title: "abuse her as an exercise in who she or she is",
        body: "and the just, but blinded by the pleasure of every right to choose, or for the pleasure of the pains or the accusers, who can bear the annoyances of his hatred and labor and desire",
        photo: "/assets/posts/post3.jpg",
        date: "10 hours ago",
        like: "10",
        comment: "30",
    },

    {
        userId: 3,
        id: 4,
        title: "ea molestias quasi exercitationem repellat qui ipsa sit aut",
        body: "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut",
        photo: "/assets/posts/post4.jpg",
        date: "23 hours ago",
        like: "10",
        comment: "30",
    },
    {
        userId: 4,
        id: 5,
        title: "know how to hate",
        body: "to be rejected is to seek pardon but to be rejected or to shun",
        photo: "/assets/posts/post5.jpg",
        date: "2 days ago",
        like: "560",
        comment: "200",
    },
    {
        userId: 2,
        id: 6,
        title: "I will open them for my great sorrow",
        body: "so that no one will reject the body of these women who provide us with a softness to follow, and no one will find fault with those accusing us of whatever pains he desires, and the pain of annoyance",
        photo: "/assets/posts/post6.jpg",
        date: "2 days ago",
        like: "130",
        comment: "31",
    },
    {
        userId: 1,
        id: 7,
        title: "great but easy",
        body: "the pain may please some people in the life where it is important, for who who, by whom no one, or whom no one will often drive back, will receive them as because they want to follow them, but which they are",
        photo: "/assets/posts/post7.jpg",
        date: "2 weeks ago",
        like: "10",
        comment: "30",
    },
    {
        userId: 4,
        id: 8,
        title: "pain is the actual pain",
        body: "I will open the pain to those who are worthy of being easily accepted by some minds who are able to be able to receive great things when there has never been greater",
        photo: "/assets/posts/post8.jpg",
        date: "3 weeks ago",
        like: "780",
        comment: "412",
    },
    {
        userId: 1,
        id: 9,
        title: "know the right time and the pain of all the accusers",
        body: "",
        photo: "/assets/posts/post9.jpg",
        date: "2 months ago",
        like: "10",
        comment: "3",
    },
    {
        userId: 2,
        id: 10,
        title: "choice that's annoying for him",
        body: "in which manner and unencumbered with the duties or great sorrows which must be repudiated, unless there be truly any pardon which but we accuse the error of the truth",
        photo: "/assets/posts/post10.jpg",
        date: "4 months ago",
        like: "86",
        comment: "12",
    },

];